language: python
python:
    - '2.7'
    - '3.5'
before_install:
    - sudo apt-get install libhdf5-7 hdf5-tools libnetcdf-dev netcdf-bin
install:
    - pip install --upgrade pytest coverage codecov
    - pip install -r requirements.txt
script:
    - coverage run --source splitvar -m py.test
after_success:
    - codecov
# deploy:
#   provider: pypi
#   user:
#   password:
#     secure: 
#   on:
#     tags: true
#     repo: aidanheerdegen/splitvar
#   distributions: "sdist bdist_wheel"
